// <auto-generated />
using LimespotAssignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LimespotAssignment.Migrations
{
    [DbContext(typeof(TransformersDbContext))]
    partial class TransformersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LimespotAssignment.Data.Domain.Entities.SpecialTransformerNames", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive");

                    b.Property<string>("TransformerName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("SpecialNames");

                    b.HasData(
                        new { ID = 1, IsActive = true, TransformerName = "Predaking" },
                        new { ID = 2, IsActive = true, TransformerName = "Optimus" }
                    );
                });

            modelBuilder.Entity("LimespotAssignment.Data.Domain.Entities.Transformer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Allegiance");

                    b.Property<int>("Courage");

                    b.Property<int>("Endurance");

                    b.Property<int>("Firepower");

                    b.Property<int>("Intelligence");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsSpecial");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Rank");

                    b.Property<int>("Skill");

                    b.Property<int>("Speed");

                    b.Property<int>("Strength");

                    b.HasKey("ID")
                        .HasName("PK_ID");

                    b.HasIndex("Name")
                        .HasName("IX_Name")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Transformers");
                });
#pragma warning restore 612, 618
        }
    }
}
